INSERT INTO vagas (CODIGO_VAGA, STATUS_VAGA) 
select '1A1', 0 from dual union all 
select '1A2', 0 from dual union all 
select '1A3', 0 from dual union all 
select '1A4', 0 from dual union all 
select '1A5', 0 from dual union all 
select '1A6', 0 from dual union all 
select '1A7', 0 from dual union all 
select '1A8', 0 from dual union all 
select '1A9', 0 from dual union all 
select '1A10', 0 from dual union all
select '1A11', 0 from dual union all
select '1A12', 0 from dual union all
select '1A13', 0 from dual union all
select '1A14', 0 from dual union all
select '1A15', 0 from dual union all
select '1B1', 0 from dual union all
select '1B2', 0 from dual union all
select '1B3', 0 from dual union all
select '1B4', 0 from dual union all
select '1B5', 0 from dual union all
select '1B6', 0 from dual union all
select '1B7', 0 from dual union all
select '1B8', 0 from dual union all
select '1B9', 0 from dual union all
select '1B10', 0 from dual union all
select '1B11', 0 from dual union all
select '1B12', 0 from dual union all
select '1B13', 0 from dual union all
select '1B14', 0 from dual union all
select '1B15', 0 from dual union all
select '1C1', 0 from dual union all
select '1C2', 0 from dual union all
select '1C3', 0 from dual union all
select '1C4', 0 from dual union all
select '1C5', 0 from dual union all
select '1C6', 0 from dual union all
select '1C7', 0 from dual union all
select '1C8', 0 from dual union all
select '1C9', 0 from dual union all
select '1C10', 0 from dual union all
select '1C11', 0 from dual union all
select '1C12', 0 from dual union all
select '1C13', 0 from dual union all
select '1C14', 0 from dual union all
select '1C15', 0 from dual union all
select '1D1', 0 from dual union all
select '1D2', 0 from dual union all
select '1D3', 0 from dual union all
select '1D4', 0 from dual union all
select '1D5', 0 from dual union all
select '1D6', 0 from dual union all
select '1D7', 0 from dual union all
select '1D8', 0 from dual union all
select '1D9', 0 from dual union all
select '1D10', 0 from dual union all
select '1D11', 0 from dual union all
select '1D12', 0 from dual union all
select '1D13', 0 from dual union all
select '1D14', 0 from dual union all
select '1D15', 0 from dual union all
select '2A1', 0 from dual union all
select '2A2', 0 from dual union all
select '2A3', 0 from dual union all
select '2A4', 0 from dual union all
select '2A5', 0 from dual union all
select '2A6', 0 from dual union all
select '2A7', 0 from dual union all
select '2A8', 0 from dual union all
select '2A9', 0 from dual union all
select '2A10', 0 from dual union all
select '2A11', 0 from dual union all
select '2A12', 0 from dual union all
select '2A13', 0 from dual union all
select '2A14', 0 from dual union all
select '2A15', 0 from dual union all
select '2B1', 0 from dual union all
select '2B2', 0 from dual union all
select '2B3', 0 from dual union all
select '2B4', 0 from dual union all
select '2B5', 0 from dual union all
select '2B6', 0 from dual union all
select '2B7', 0 from dual union all
select '2B8', 0 from dual union all
select '2B9', 0 from dual union all
select '2B10', 0 from dual union all
select '2B11', 0 from dual union all
select '2B12', 0 from dual union all
select '2B13', 0 from dual union all
select '2B14', 0 from dual union all
select '2B15', 0 from dual union all
select '2C1', 0 from dual union all
select '2C2', 0 from dual union all
select '2C3', 0 from dual union all
select '2C4', 0 from dual union all
select '2C5', 0 from dual union all
select '2C6', 0 from dual union all
select '2C7', 0 from dual union all
select '2C8', 0 from dual union all
select '2C9', 0 from dual union all
select '2C10', 0 from dual union all
select '2C11', 0 from dual union all
select '2C12', 0 from dual union all
select '2C13', 0 from dual union all
select '2C14', 0 from dual union all
select '2C15', 0 from dual union all
select '2D1', 0 from dual union all
select '2D2', 0 from dual union all
select '2D3', 0 from dual union all
select '2D4', 0 from dual union all
select '2D5', 0 from dual union all
select '2D6', 0 from dual union all
select '2D7', 0 from dual union all
select '2D8', 0 from dual union all
select '2D9', 0 from dual union all
select '2D10', 0 from dual union all
select '2D11', 0 from dual union all
select '2D12', 0 from dual union all
select '2D13', 0 from dual union all
select '2D14', 0 from dual union all
select '2D15', 0 from dual union all
select '3A1', 0 from dual union all
select '3A2', 0 from dual union all
select '3A3', 0 from dual union all
select '3A4', 0 from dual union all
select '3A5', 0 from dual union all
select '3A6', 0 from dual union all
select '3A7', 0 from dual union all
select '3A8', 0 from dual union all
select '3A9', 0 from dual union all
select '3A10', 0 from dual union all
select '3A11', 0 from dual union all
select '3A12', 0 from dual union all
select '3A13', 0 from dual union all
select '3A14', 0 from dual union all
select '3A15', 0 from dual union all
select '3B1', 0 from dual union all
select '3B2', 0 from dual union all
select '3B3', 0 from dual union all
select '3B4', 0 from dual union all
select '3B5', 0 from dual union all
select '3B6', 0 from dual union all
select '3B7', 0 from dual union all
select '3B8', 0 from dual union all
select '3B9', 0 from dual union all
select '3B10', 0 from dual union all
select '3B11', 0 from dual union all
select '3B12', 0 from dual union all
select '3B13', 0 from dual union all
select '3B14', 0 from dual union all
select '3B15', 0 from dual union all
select '3C1', 0 from dual union all
select '3C2', 0 from dual union all
select '3C3', 0 from dual union all
select '3C4', 0 from dual union all
select '3C5', 0 from dual union all
select '3C6', 0 from dual union all
select '3C7', 0 from dual union all
select '3C8', 0 from dual union all
select '3C9', 0 from dual union all
select '3C10', 0 from dual union all
select '3C11', 0 from dual union all
select '3C12', 0 from dual union all
select '3C13', 0 from dual union all
select '3C14', 0 from dual union all
select '3C15', 0 from dual union all
select '3D1', 0 from dual union all
select '3D2', 0 from dual union all
select '3D3', 0 from dual union all
select '3D4', 0 from dual union all
select '3D5', 0 from dual union all
select '3D6', 0 from dual union all
select '3D7', 0 from dual union all
select '3D8', 0 from dual union all
select '3D9', 0 from dual union all
select '3D10', 0 from dual union all
select '3D11', 0 from dual union all
select '3D12', 0 from dual union all
select '3D13', 0 from dual union all
select '3D14', 0 from dual union all
select '3D15', 0 from dual union all
select '4A1', 0 from dual union all
select '4A2', 0 from dual union all
select '4A3', 0 from dual union all
select '4A4', 0 from dual union all
select '4A5', 0 from dual union all
select '4A6', 0 from dual union all
select '4A7', 0 from dual union all
select '4A8', 0 from dual union all
select '4A9', 0 from dual union all
select '4A10', 0 from dual union all
select '4A11', 0 from dual union all
select '4A12', 0 from dual union all
select '4A13', 0 from dual union all
select '4A14', 0 from dual union all
select '4A15', 0 from dual union all
select '4B1', 0 from dual union all
select '4B2', 0 from dual union all
select '4B3', 0 from dual union all
select '4B4', 0 from dual union all
select '4B5', 0 from dual union all
select '4B6', 0 from dual union all
select '4B7', 0 from dual union all
select '4B8', 0 from dual union all
select '4B9', 0 from dual union all
select '4B10', 0 from dual union all
select '4B11', 0 from dual union all
select '4B12', 0 from dual union all
select '4B13', 0 from dual union all
select '4B14', 0 from dual union all
select '4B15', 0 from dual union all
select '4C1', 0 from dual union all
select '4C2', 0 from dual union all
select '4C3', 0 from dual union all
select '4C4', 0 from dual union all
select '4C5', 0 from dual union all
select '4C6', 0 from dual union all
select '4C7', 0 from dual union all
select '4C8', 0 from dual union all
select '4C9', 0 from dual union all
select '4C10', 0 from dual union all
select '4C11', 0 from dual union all
select '4C12', 0 from dual union all
select '4C13', 0 from dual union all
select '4C14', 0 from dual union all
select '4C15', 0 from dual union all
select '4D1', 0 from dual union all
select '4D2', 0 from dual union all
select '4D3', 0 from dual union all
select '4D4', 0 from dual union all
select '4D5', 0 from dual union all
select '4D6', 0 from dual union all
select '4D7', 0 from dual union all
select '4D8', 0 from dual union all
select '4D9', 0 from dual union all
select '4D10', 0 from dual union all
select '4D11', 0 from dual union all
select '4D12', 0 from dual union all
select '4D13', 0 from dual union all
select '4D14', 0 from dual union all
select '4D15', 0 from dual union all
select '5A1', 0 from dual union all
select '5A2', 0 from dual union all
select '5A3', 0 from dual union all
select '5A4', 0 from dual union all
select '5A5', 0 from dual union all
select '5A6', 0 from dual union all
select '5A7', 0 from dual union all
select '5A8', 0 from dual union all
select '5A9', 0 from dual union all
select '5A10', 0 from dual union all
select '5A11', 0 from dual union all
select '5A12', 0 from dual union all
select '5A13', 0 from dual union all
select '5A14', 0 from dual union all
select '5A15', 0 from dual union all
select '5B1', 0 from dual union all
select '5B2', 0 from dual union all
select '5B3', 0 from dual union all
select '5B4', 0 from dual union all
select '5B5', 0 from dual union all
select '5B6', 0 from dual union all
select '5B7', 0 from dual union all
select '5B8', 0 from dual union all
select '5B9', 0 from dual union all
select '5B10', 0 from dual union all
select '5B11', 0 from dual union all
select '5B12', 0 from dual union all
select '5B13', 0 from dual union all
select '5B14', 0 from dual union all
select '5B15', 0 from dual union all
select '5C1', 0 from dual union all
select '5C2', 0 from dual union all
select '5C3', 0 from dual union all
select '5C4', 0 from dual union all
select '5C5', 0 from dual union all
select '5C6', 0 from dual union all
select '5C7', 0 from dual union all
select '5C8', 0 from dual union all
select '5C9', 0 from dual union all
select '5C10', 0 from dual union all
select '5C11', 0 from dual union all
select '5C12', 0 from dual union all
select '5C13', 0 from dual union all
select '5C14', 0 from dual union all
select '5C15', 0 from dual union all
select '5D1', 0 from dual union all
select '5D2', 0 from dual union all
select '5D3', 0 from dual union all
select '5D4', 0 from dual union all
select '5D5', 0 from dual union all
select '5D6', 0 from dual union all
select '5D7', 0 from dual union all
select '5D8', 0 from dual union all
select '5D9', 0 from dual union all
select '5D10', 0 from dual union all
select '5D11', 0 from dual union all
select '5D12', 0 from dual union all
select '5D13', 0 from dual union all
select '5D14', 0 from dual union all
select '5D15', 0 from dual;